Add controllers
MR-k0f31n/java-shareit pull request #3
Opened 2023-05-01 06:54 UTC by MR-k0f31n

2023-05-01 07:48 UTC, MR-k0f31n commented
Hola, Mr. sénior Alejandro! mr code style says hello to me

2023-05-02 08:09 UTC, TomattmanYandex requested changes
Привет, коменты как обычно в коде
Дополнительный коммент относительно пакетов
При таком подходе как в этом проекте (по разбиению на пакеты) обычно делают пакет для типа обьектов а уже внутри не делают дополнительного разбиения на пакеты, т.е. пакет items и в нем все классы относящиеся к нему без подпакетов

2023-05-02 08:09 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    private Enum<Status> status;
зачем тут Enum<Status> для того чтобы использовать перечисление обьявляем переменную с типом этого перечисления private Status status;

2023-05-02 08:09 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto createNewItem(@RequestHeader("X-Sharer-User-Id") Long ownerId, @Valid @RequestBody Item item) {
на уровне контроллера работаем с DTO не только на возврат значение но и на обьекты параметров

2023-05-02 08:09 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        log.debug("Endpoint request: 'GET /items/{search}'");
search это get параметр они не так отображаются

2023-05-02 08:09 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/repository/InMemoryItemStorage.java
> +        return toItemDto(items.get(id));
превращение в DTO и обратно это уровень сервиса, точно не хранилища

2023-05-02 08:09 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/repository/InMemoryItemStorage.java
> +    public boolean checkItem(Long id) {
что значит checkItem? имя стоит поменять

2023-05-02 08:09 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (!repository.checkItem(id)) {
зачем делать два запроса к базе когда хватит одного, сделали запрос обьекта по id Если вернется null или optional .empty тогда объекта нету, кидаем ошибку, иначе у нас уже есть обьект с которым можно работать

2023-05-02 08:09 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    @Email
аннотации для валидации могут быть только на Dto потому что только через них мы общаемся с внешним миром, а сущности базы уже можно так не валдиировать

2023-05-02 08:09 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/user/repository/InMemoryUserStorage.java
> +            usersDto.add(toUserDto(user));
и снова перевод в dto и обратно делаем на уровне сервиса

2023-05-02 08:09 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/util/RowMapper.java
> +public class RowMapper {
1) это не ROW mapper а просто маппер если хочется добавить префик то лучше подойдет DtoMapper 
2) лучше сделать отдельный маппер для каждого типа обьектов и этот маппер поместить к этому обьекту в пакет
3) необходимо также добавить методы для перевода из обьекта в DTO

2023-05-02 08:16 UTC, MR-k0f31n commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    private Enum<Status> status;
а я тупая лошадь думал что все эти классы нужно будет реализовывать, вот начал заполнять, а потом дошло до страуса

2023-05-02 08:25 UTC, MR-k0f31n commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (!repository.checkItem(id)) {
согласне, забыл наверное что если обьекта нет в мапе вернется null или NPE испугался словить))

2023-05-04 16:18 UTC, TomattmanYandex requested changes
Привет, все хорошо, исправить совсем немного 
1) сделать вместо двух классов маппера для item - один но с двумя методами
2) то что в в пакетах user.dto и user.model перекинуть в пакет user, и то же самое для итемов

2023-05-04 16:18 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/dto/ItemDtoMapper.java
> +    public static ItemDto toItemDto(Item item) {
зачем нам два класса мапера, достаточно одного, который будет иметь два метода один превращающий в дто второй из дто в обьект

2023-05-04 16:18 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        return toItemDto(repository.createItem(toItem(itemDto)));
вроде все правильно но понять тяжело
может вынести в переменную что нибудь?

2023-05-04 16:36 UTC, MR-k0f31n commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        return toItemDto(repository.createItem(toItem(itemDto)));
ok

2023-05-04 16:37 UTC, MR-k0f31n commented on src/main/java/ru/practicum/shareit/item/dto/ItemDtoMapper.java
> +    public static ItemDto toItemDto(Item item) {
ok

2023-05-04 16:40 UTC, MR-k0f31n commented
knock knock MR Anderson

2023-05-04 16:57 UTC, TomattmanYandex approved these changes
ПРинято

2023-05-04 17:33 UTC, TomattmanYandex approved these changes
+

2023-05-04 19:04 UTC, merged