Add bookings
MR-k0f31n/java-shareit pull request #4
Opened 2023-05-22 09:21 UTC by MR-k0f31n

Add booking, repository from JPA.
Add users repository  from JPA.
Add items repository  from JPA.
Add comments repository  from JPA.

2023-05-22 19:55 UTC, TomattmanYandex requested changes
Отличная работа, в оснвовном изменения для красивой читаемости и удообности, некоторые моменты поментил только в одном классе, то следует посмотреть во всех соответствующих

2023-05-22 19:55 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public BookingDto createNewBooking(@RequestBody @Valid BookingInputDTO bookingInputDTODto, @RequestHeader("X-Sharer-User-Id") Long userId) {
Зачем обзывать переменную bookingInputDTODto
ведь в методе будет только один букинг обьект следовательно хватило бы простого booking или bookingDto и бац читать сразу приятнее
(плюс два дто в конце)

2023-05-22 19:55 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingItemBookerDto.java
> +public class BookingItemBookerDto {
очень невнятное название

2023-05-22 19:55 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +    public static Booking toBooking(BookingDto bookingDto) {
я бы назвал методы dtoToObject и objectToDto так у всех мапперов названия методов были бы одинаковые
а метод на преобразование списка, перегрузил бы параметром, один элемент - обрабатываем один букинг, лист элементов, обрабатываем список

2023-05-22 19:55 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/comment/Comment.java
> +package ru.practicum.shareit.comment;
коменты относятся больше к айтемам, можно было бы поместить в пакет item т.е. пакет itemв нем все про Item и в нем же пакет comment

2023-05-23 07:36 UTC, MR-k0f31n commented on src/main/java/ru/practicum/shareit/booking/BookingItemBookerDto.java
> +public class BookingItemBookerDto {
+

2023-05-23 07:36 UTC, MR-k0f31n commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public BookingDto createNewBooking(@RequestBody @Valid BookingInputDTO bookingInputDTODto, @RequestHeader("X-Sharer-User-Id") Long userId) {
косяк

2023-05-23 07:36 UTC, MR-k0f31n commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +    public static Booking toBooking(BookingDto bookingDto) {
выбрал лучшее название

2023-05-23 07:36 UTC, MR-k0f31n commented on src/main/java/ru/practicum/shareit/comment/Comment.java
> +package ru.practicum.shareit.comment;
зарефакторили

2023-05-23 18:11 UTC, TomattmanYandex approved these changes
Принято

2023-05-24 06:14 UTC, merged