Add item requset, add pageable
MR-k0f31n/java-shareit pull request #5
Opened 2023-06-02 14:22 UTC by MR-k0f31n

<Add> request function.
<Complete> test postman
<Next> unit test

2023-06-02 14:33 UTC, MR-k0f31n commented
ахаха, прикольно, тесты он тоже пройти до конца не может т.к. покрытие кода не то что ожидалось))

2023-06-03 09:53 UTC, TomattmanYandex requested changes
коменты в коде, когда отправляешь на проверку, убеждайся, что автоматические проверки прошли, если они не прошли, я могу просто не смотря код отправить на переделку

2023-06-03 09:53 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/Item.java
> +    private Long requestId;
раз теперь есть сущность в базе, надо переменную заводить на саму сущность, пример на строчку выше

2023-06-03 09:53 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +                                                                                                     String text2,
кажись что то с форматированием

2023-06-03 09:53 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/request/ItemRequestRepository.java
> +    List<ItemRequest> findAllByRequesterIdOrderByCreatedDateDesc(Long userId);
а этот запрос не должен быть постраничным?

2023-06-03 09:53 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/user/UserControllerTest.java
> +    void testGetAllUserExpectedLength2_correct() throws Exception {
в именовании тестовых методов, можно использовать два слова Should должен и When когда,
название тестируемого метода Shoud что должен делать When при каком условии
Например 
getAllUserShouldReturn2EntriesWhenExist2Users
но со словами читать не так удобно
гораздо легче воспринимается с нижними подчеркиваниями (заменяют оба слова)
getAllUser_return2Entries_exist2Users
так для того чтобы понять что просходит даже не обязательно читать все имя метода, нижние подчеркивания отлично разделяют на части

2023-06-03 09:53 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/user/UserControllerTest.java
> +    void testCreateUserWithEmailWrong_expectedError() throws Exception {
этот тестовый метод стоит разделить на несколько, под каждый случай свой тестовый метод, и возможно из имена будут различаться только в поледней части
это лучше потому что, если упадет первая проверка, остальные даже не будут выполнены, а если будет несколько тестов, то выполнены будут все, и можно понять будет что и как там

2023-06-03 09:53 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/user/UserServiceTest.java
> +        userRepository = Mockito.mock(UserRepository.class);
у спринга есть способы как аннотациями создать замоканые объекты
и почему один репозиторий замокан, а второй нет

2023-06-03 09:53 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/user/UserServiceTest.java
> +    void testGetAllUser_correct() {
юнит тест такого не имеет особого смысла,
юнит тесты лучше делать на методы которые имеют какую нибудь сложную внутренню логику, чтобы протестировать именно эту логику
а если вся суть метода в том чтобы вернуть данные из репозитория, то лучше интеграционный тест на это сделать

хороший вариант на юнит тест, например сделать проверку что если мы запроси вещи не своего пользователя, что они не вернутся

2023-06-05 08:28 UTC, MR-k0f31n commented on src/main/java/ru/practicum/shareit/item/Item.java
> +    private Long requestId;
спасибо, помучался))

2023-06-05 08:29 UTC, MR-k0f31n commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +                                                                                                     String text2,
если сделать в строку то пейдж выхоидт за 140 симовлов

2023-06-05 08:39 UTC, MR-k0f31n commented on src/main/java/ru/practicum/shareit/request/ItemRequestRepository.java
> +    List<ItemRequest> findAllByRequesterIdOrderByCreatedDateDesc(Long userId);
В описании не было, хорошо - добавил)

2023-06-05 08:40 UTC, MR-k0f31n commented on src/test/java/ru/practicum/shareit/user/UserControllerTest.java
> +    void testGetAllUserExpectedLength2_correct() throws Exception {
+

2023-06-05 13:46 UTC, MR-k0f31n commented on src/test/java/ru/practicum/shareit/user/UserControllerTest.java
> +    void testCreateUserWithEmailWrong_expectedError() throws Exception {
сделал

2023-06-05 20:00 UTC, MR-k0f31n commented on src/test/java/ru/practicum/shareit/user/UserServiceTest.java
> +        userRepository = Mockito.mock(UserRepository.class);
исправил

2023-06-05 20:00 UTC, MR-k0f31n commented on src/test/java/ru/practicum/shareit/user/UserServiceTest.java
> +    void testGetAllUser_correct() {
попробовал сделать в точности как учил

2023-06-09 07:40 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        Pageable pageable = PageRequest.of(from / size, size);
Так как тут присутствует какая то логика и подсчеты, и повторяется это множество раз, то лучше сделать отдельный метод и создавать PageRequest через него 
Это может пригодится, если вдруг поменяются условия, например в качестве параметра будет приходить не элемент с которого надо отдать, а страница, в текущем варианте, прийдется искать все создания PageRequest и изменять, а в том что я предлагаю, только в одном месте изменил и готово

2023-06-09 07:40 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/request/ItemRequestRepository.java
> +    List<ItemRequest> findAllByRequesterIdOrderByCreatedDateDesc(Long userId);
Это был только вопрос, если в задании не было, значит оно и не надо

2023-06-09 08:02 UTC, TomattmanYandex requested changes
Привет
1) в тесте букинг сервиса я оставил коммент по поводу теста, проверь это во всех тестах 
2) по условию должны быть отдельные тесты репозитория

2023-06-09 08:02 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +        when(service.createNewBooking(any(BookingInputDto.class), anyLong())).thenReturn(bookingDto);
минус этого замоканного теста в том, что ты не узнаешь, вызван ли сервис с нужными параметрами, или с какими то левыми, тут лучше подошел бы вариант не с any() и anyLong() а например с параметрами равными какому то конкретному значению

2023-06-09 08:02 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingServiceTest.java
> +    void checkCreateNewItemUserAndBooking() {
обычно тесты соответствуют структуре given when then 
такие блоки даже добавляют разделением комментариями в коде
//given
подготовка теста (моки, создание записи в базе и т.д.)
//when
выполнение тестируемого метода
//then
проверки

текущий тест выглядит очень странно, мы просто берем какую то переменную и сверяем ее поля с полями какой то другой переменной, что за переменная, где мы ее взяли, где вообще вызов метода, это не понятно

Если надо проверить создание, то лучше либо создать еще один обьект в базе и сверять его, либо хотя бы в этом методе получить обьект из базы, чтобы понять что мы сравниваем
Второй момент, у тебя есть метод в сервисе, который тестируешь, ты передал в него обьект, получил обратно другой обьект и сверяешь их, что будет если код сервисного метода будет примерно таким
public BookingResponseDto createBooking(BookingRequestDto reuestDto) {
return mapper.mapRequestDtoToResponseDtro();
}
псевдокодный псевдокод, но примерно суть должна быть понятна

В этом случае тест все равно пройдет, хотя в базе ничего не появится, именно для таких случаев в интеграционных тестах следует брать данные с разных уровней, например тестируем создание обьекта в сервисе, выполнили код, который создает обьект, но для сравнения обьект получили из репозитория напрямую

2023-06-09 09:10 UTC, MR-k0f31n commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        Pageable pageable = PageRequest.of(from / size, size);
Согласен, пока искал замучался) а когда делал до такого не додумался

2023-06-09 11:01 UTC, MR-k0f31n commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +        when(service.createNewBooking(any(BookingInputDto.class), anyLong())).thenReturn(bookingDto);
Надеюсь это была рекомендация

2023-06-09 11:02 UTC, MR-k0f31n commented on src/test/java/ru/practicum/shareit/booking/BookingServiceTest.java
> +    void checkCreateNewItemUserAndBooking() {
Согласен, фигню сморозил

2023-06-10 09:04 UTC, TomattmanYandex approved these changes
Принято

2023-06-10 09:04 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingServiceTest.java
> +    void checkCreateNewItemUserAndBooking() {
хитрый способ, удалить тест, чтобы не исправлять

2023-06-10 15:42 UTC, merged