<TO DO> split program on two microservice - gateway and server. <ADD>…
MR-k0f31n/java-shareit pull request #6
Opened 2023-06-14 20:52 UTC by MR-k0f31n

split program on two microservices - gateway and server
add docker image

2023-06-15 07:08 UTC, MR-k0f31n commented
Бью все рекорды всего 4 коммита =))

2023-06-15 13:19 UTC, TomattmanYandex requested changes
пара изменений нужны

2023-06-15 13:19 UTC, TomattmanYandex commented on server/src/main/java/ru/practicum/shareit/booking/BookingInputDto.java
тут остались аннотации валидации надо бы их поудалять, здесь и в остальных DTO

2023-06-15 13:19 UTC, TomattmanYandex commented on server/pom.xml
> +        <dependency>
Зачем тут эта зависимость если мы больше тут не валидируем

2023-06-15 13:39 UTC, MR-k0f31n commented on server/src/main/java/ru/practicum/shareit/booking/BookingInputDto.java
Чоооорт , я совсем про них забыл

2023-06-15 13:43 UTC, MR-k0f31n commented on server/pom.xml
> +        <dependency>
ок

2023-06-16 11:01 UTC, TomattmanYandex approved these changes
Принято

2023-06-16 11:15 UTC, merged